on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: "24.10.0"
    - run: |
       npm install
       ./node_modules/.bin/prettier --write "./main.js"
       git diff --exit-code
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        sbt:
        - "1"
        - "2"
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 8
    - uses: sbt/setup-sbt@v1
    - run: mkdir project
    - run: |
        case ${{ matrix.sbt }} in
          "1")
            echo "sbt.version=1.11.7" > project/build.properties
            ;;
          "2")
            echo "sbt.version=2.0.0-RC6" > project/build.properties
            ;;
          *)
            echo "unknown version"
            exit 1
        esac
    - run: sbt --server -Dsbt.traces=true Test/compile
    - uses: ./
      with:
        min-duration: 2
